### ISSUE TITLE
Ylimääräiset merkit tietueiden titlejen lopussa

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-report-services#1]
### Mikä vikana?

Siistitään tarvittaessa niteistä kerätyt titlet niin, että pisteet, kenoviivat, kauttaviivat yms. otetaan niiden lopusta pois. Varmistetaan ensin onko tälle tarvetta.

**Comment by AnneliO** [comment]
Kohassa on olemassa funktio, joka poistaa ylimääräisiä merkkejä. Sitä voisi ehkä hyödyntää.

**Comment by emta001** [comment]
Jaahas, tämä on tainnut liittyä (edelleen jäissä olevaan) Raportteri-plugariin, mutta unohtunut vain siirtää tämä oikeaan repoon :D

**Comment by emta001** [comment]
Eikun olihan tämä oikeessa paikassa, hämmäännyin.

**Comment by emta001** [comment]
Ei korjata.
