### ISSUE TITLE
Raportteri: Rajapinta Koha SQL-raporttien haulle

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-report-services#2]
### Kehitysehdotukseni

Pluginiin on kehitetty API-endpoint, jonka avulla Kohasta voidaan hakea SQL-raportteja käytettäväksi esim. PowerBi:ssä. Raportit haetaan niiden id:llä ja haettavissa olevat raportit on määritetty Raportteri-pluginin asetuksissa. Endpointin käyttö vaatii OAuth-tunnistautumisen. Raportit palautetaan JSON-muodossa.

**Comment by johannaraisa** [comment]
Oliko tämä jo tehty?

**Comment by emta001** [comment]
> Oliko tämä jo tehty?

Jaa-a vai vaatiiko viellä kehitystä ja testausta nyt kun siellä on ne parametritkin? @lmstrand ?

**Comment by lmstrand** [comment]
Dokumentaatio lisätty repon readmehen ja wikiin.
